#! /usr/bin/env bash
# Script to fetch and rebase openssl branches

test -f ./config || {
    echo Not at top-level
    exit 1
}

git checkout --quiet openssl-3.0 ; git pull --rebase
git checkout --quiet openssl-3.2 ; git pull --rebase
git checkout --quiet openssl-3.3 ; git pull --rebase
git checkout --quiet openssl-3.4 ; git pull --rebase
git checkout --quiet openssl-3.5 ; git pull --rebase
git checkout --quiet master
git rebase -p origin/master

for B in `git branch | fgrep -v '*'` ; do
    case "$B" in
    OpenSSL*-stable)
        echo "        skipping $B"
        ;;
    openssl-*)
        echo "        skipping $B"
        ;;
    *)
        # If .skiplist exists and this branch is listed, don't rebase
        if test -f .skiplist && grep -q "$B" .skiplist ; then
            echo "        skipping $B"
        else
            git checkout --quiet $B
            git rebase master || exit 1
        fi
        ;;
    esac
done

git checkout --quiet master
