#! /bin/bash

# If one arg, intuit commit id from master

case $# in
2)
    id=$1
    b=$2
    ;;
1)
    id=`git branch -v | awk '$2=="master" { print $3; }'`
    b=$1
    ;;
*)
    echo Usage $0 "[commitid] branch"
    exit 1
    ;;
esac


case $b in
*1*0*1*)
    branch=OpenSSL_1_0_1-stable
    ;;
*1*0*2*)
    branch=OpenSSL_1_0_2-stable
    ;;
*1*1*0*)
    branch=OpenSSL_1_1_0-stable
    ;;
m*)
    branch=master
    ;;
*)
    echo Unknown branch
    exit 1
    ;;
esac
exec echo id,b $id $branch

echo $branch
git co --quiet master || exit 1
git co $branch || exit 1
git cherry-pick -e -x $id

echo -n 'Git push (ctrl-c to cancel): '
read x
git push
git co master
