#! /bin/bash

# If one arg, intuit commit id from master

case $# in
2)
    id=$1
    b=$2
    ;;
1)
    id=`git branch -v | awk '$2=="master" { print $3; }'`
    b=$1
    ;;
*)
    echo "Usage $0 [commitid] branch"
    exit 1
    ;;
esac


case $b in
*1*0*1*)
    branch=OpenSSL_1_0_1-stable
    ;;
*1*0*2*)
    branch=OpenSSL_1_0_2-stable
    ;;
*1*1*0*)
    branch=OpenSSL_1_1_0-stable
    ;;
m*)
    branch=master
    ;;
*)
    echo Unknown branch
    exit 1
    ;;
esac

echo "id is $id"
echo "branch is $branch"
echo "Are these correct?"

while true
do
    echo -n "Enter YES to continue or NO to abort: "
    read x
    x="`echo $x | tr A-Z a-z`"
    if [ "$x" = "y" -o "$x" = "yes" -o "$x" = "n" -o "$x" = "no" ]
    then
        break
    fi
done

if [ "$x" = "n" -o "$x" = "no" ]
then
    exit 1
fi

git checkout --quiet master || exit 1
git checkout $branch || exit 1
git cherry-pick -e -x $id

while true
do
    echo -n "Enter YES to push or NO to abort: "
    read x
    x="`echo $x | tr A-Z a-z`"
    if [ "$x" = "y" -o "$x" = "yes" -o "$x" = "n" -o "$x" = "no" ]
    then
        break
    fi
done

if [ "$x" = "y" -o "$x" = "yes" ]
then
    git push
fi

git checkout master
