#! /bin/bash

here=$(cd $(dirname $0); pwd)
rcd=$here/.run-checker-data

# The top directory has this layout:
#
#    $rcd/new   directory with new stuff...  it mostly works as a lock
#
mkdir -p $rcd

if ! mkdir $rcd/new; then
    echo >&2 "There's already a run-checker running"
    exit 1
fi

# Copy things that are of interest to the rest of the hooks.  This allows
# the original files to be added/changed without disturbing *this* run.
if [ -f $here/hook-config ]; then
    cp $here/hook-config $rcd/new
fi

if [ -f $here/rc-force-build ]; then
    mv $here/rc-force-build $rcd/new
fi

# Every build is expected to have its own cur and new layout.  For build
# of option 'no-foo', the expected layout is:
#
#    $rcd/builds/no-foo/new     New stuff
#    $rcd/builds/no-foo/cur     Stuff from the previous build
#
mkdir -p $rcd/builds

echo Starting on $(LANG=C date)
if (
    set -e

    cd openssl
    git pull --rebase
    git rev-parse HEAD > $rcd/new/head
    git rev-parse --abbrev-ref HEAD > $rcd/new/branch
); then
    exit 0
fi

# Something went wrong.  Clear away $rcd/new so it doesn't stop a later run
rm -rf $rcd/new
exit 1
