#!/usr/bin/env bash
#
# Copyright 2018-2023 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the OpenSSL license (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

this_year=`date +%Y`
some_year="[12][0-9][0-9][0-9]"
year_range="(${some_year})(-${some_year})?"

copyright_owner="The OpenSSL Project"
copyright="Copyright .*${year_range} .*${copyright_owner}"

# sed_script:
#   for all lines that contain ${copyright} : {
#     replace years yyyy-zzzz (or year yyyy) by yyyy-${this_year}
#     replace repeated years yyyy-yyyy by yyyy
#   }
ss=/tmp/sed$$
cat <<EOF >$ss
/${copyright}/ {
s|${year_range}|\1-${this_year}|
s|(${some_year})-\1|\1|
}
EOF

collect_files() {
    NYD=`date +%Y-01-01`

    git diff-tree -r --name-status `git rev-list -1 --before=$NYD HEAD`..HEAD | \
    grep -v '^ *D'

    # Always update the end year in README.md and/or README.
    # It might be listed twice, but this is hardly a problem,
    # just slightly suboptimal.
    [[ -f README.md ]] && echo 'X       README.md'
    [[ -f README ]]    && echo 'X       README'
}

process_files() {
    count=0
    sp="/-\|"
    sc=0
    spin() {
	printf "\r${sp:sc++:1} %s" "$@"
	((sc==${#sp})) && sc=0
    }
    endspin() {
	printf "\r%s\n" "$@"
    }

    while read STATUS FILE ; do
	if [ -d "$FILE" ]; then continue; fi
	(( count++ ))
	spin $count
	# To avoid touching the original files when they aren't modified:
	#
	# 1. Copy the file, to make sure all permissions and other
	#	 copyable attributes are copied as well
	# 2. Run sed on the copy
	# 3. IF the copy has been modified, move it back to the original,
	#	 add and commit.
	TMPFILE="$(dirname "$FILE")"/"__$(basename "$FILE").new"
	cp "$FILE" "$TMPFILE"
	sed -E -f /tmp/sed$$ -i "$TMPFILE"
	if cmp -s "$FILE" "$TMPFILE"; then
	    rm "$TMPFILE"
	else
	    mv "$TMPFILE" "$FILE"
	    git add "$FILE"
	fi
    done
    endspin "Files considered: $count"
}

echo Updating copyright
collect_files | process_files
echo Files changed: $(git status --porcelain --untracked-files=no --ignore-submodules=all | grep '^ *M' | wc -l)
rm -f $ss
