#! /usr/bin/env perl
# Annotate the output of "get-followups -d" to show the stats
# of each commit for a "last chance trying to find" page.
use strict;
use warnings;

die "Feed this the output of 'get-followups -d'\n" if -t 0;

print <<'EOF';
<html>
  <head>
    <title>Help find these people</title>
    <link rel="stylesheet" type="text/css" href="/style.css">
  </head>
  <body>
    <h1>Help find these people</h1>
<p>
We are looking for some people who have previously contributed to OpenSSL. See
<a href="/blog/blog/2017/03/22/license/">https://www.openssl.org/blog/blog/2017/03/22/license/</a>
for some background.
</p>
If you know where to find any of the following people, please email their
current address to
<a href="mailto:license@openssl.org">license@openssl.org</a>,
or ask them to get in touch.
</p>
<p>
Each contributor is separated by a blank line.  The first line is the last
known email we have (not valid), and the full name if known.  Each following
line has the number of files changed, lines added and deleted, the commit ID
and date, and then the commit subject line.
</p>
<p>
Thank you!
</p>
<pre>
EOF

while ( <> ) {
    unless ( /([0-da-f]{8}) .*/ ) {
	s/.*uid.[0-9]+, //;
	s/, \d, /, /;
	s/"//g;
	if ( /([^,]*), (.*)/ ) {
	    if ( $1 eq $2 ) {
		print "&lt;$1>\n";
	    } else {
		print "$2 &lt;$1>\n";
	    }
	} else {
	    print;
	}
	next;
    }
    my $cid = $1;
    my $line = $_;
    $line =~ s/^\s*//;
    if ( $cid eq 'd02b48c6' ) {
	print "- +0/-0 ", $_;
	next;
    }
    my $pattern = "$cid^..$cid";
    my $files = 0;
    my $adds = 0;
    my $dels = 0;
    open my $F, "git diff --numstat $pattern|"
	|| die "Can't open git diff, $!\n";
    while ( <$F> ) {
	$files++;
	next unless /(\d+)\s+(\d+)\s+(.*)/;
	$adds += int($1);
	$dels += int($2);
    }
    close $F || die "Can't close git diff, $!\n";
    print "$files +$adds -$dels $line";
}
print <<'EOF';

    </pre>

    <a href="/">Main page</a></p>
  </body>
</html>
EOF
