#! /usr/bin/env python
"""Mark specified email accounts as approving.
"""

import datetime, mysql.connector, os, re, subprocess, sys
import string, random

dbconfig = {
        'user': 'license',
        'password': open('rwpass.txt').read().strip(),
        'database': 'license'
        }
conn = mysql.connector.connect(**dbconfig)
cursor = conn.cursor()

q = 'select uid from users where email = %s'
update = ("UPDATE users SET date_replied=%s, reply=%s, comment=%s"
     " WHERE uid=%s")
today = datetime.datetime.today().date()
reply = 'y'
comment = 'From CLI';

for email in sys.argv[1:]:
    cursor.execute(q, (email,))
    for uid in cursor:
        cursor.execute(update, (today, reply, comment, uid[0]))
        conn.commit()
