#! /usr/bin/env python
"""Arguments is a list of SQL paterns (will get wrapped in wildcards, %),
display uid email and name
"""

import mysql.connector
import datetime, os, re, subprocess, sys, string, random

dbconfig = {
        'user': 'license',
        'password': open('rwpass.txt').read().strip(),
        'database': 'license'
        }
conn = mysql.connector.connect(**dbconfig)
cursor = conn.cursor()
raw = open("request-approval.txt").read()

# Get dict of matching users
for email in sys.argv[1:]:
    q = ('SELECT uid,reply, email,name FROM users'
            ' WHERE email LIKE %s ORDER BY uid')
    pat = '%' + email + '%'
    cursor.execute(q, (pat,))
    for row in cursor:
        uid,reply,email,name = row
        if reply == None: reply = '-'
        print uid, reply, email, name
