#! /usr/bin/env python
"""Arguments is a list of SQL paterns (will get wrapped in wildcards, %),
display uid email and name
"""

import mysql.connector
import datetime, os, re, subprocess, sys, string, random

dbconfig = {
        'user': 'licensereader',
        'password': open('ropass.txt').read().strip(),
        'database': 'license'
        }
conn = mysql.connector.connect(**dbconfig)
cursor = conn.cursor()
raw = open("request-approval.txt").read()

# Get dict of matching users
for email in sys.argv[1:]:
    q = ('SELECT users.uid,email,reply,name,count(log.uid) FROM users'
            ' LEFT JOIN log ON log.uid = users.uid'
            ' WHERE email like %s GROUP BY email' );
    pat = '%' + email + '%'
    cursor.execute(q, (pat,))
    for row in cursor:
        uid,email,reply,name,count = row
        if reply == None:
            reply = '-'
        print '%d, %s, %s, %d, "%s"' % (uid, email, reply, count, name)
