#! /usr/bin/env perl
# Annotate the output of "get-followups -d" to show the summary
# of all outstanding commits.
use strict;
use warnings;

open my $FH, "./get-followups -d|" || die "Can't pipe, $!,";

my $total = 0;
my $tot_adds = 0;
my $tot_files = 0;
my $tot_dels = 0;
my $authors = 0;
while ( <$FH> ) {
    if ( /https:/ ) {
	$authors++;
	next;
    }
    next unless /([0-da-f]{8}) .*/;
    my $cid = $1;
    my $pattern = "$cid^..$cid";
    my $files = 0;
    my $adds = 0;
    my $dels = 0;
    $total++;
    open my $F, "git diff --numstat $pattern|"
	|| die "Can't open git diff, $!\n";
    while ( <$F> ) {
	next if /CHANGES/;
	$files++;
	next unless /(\d+)\s+(\d+)\s+(.*)/;
	$adds += int($1);
	$dels += int($2);
    }
    $tot_files += $files;
    $tot_adds += $adds;
    $tot_dels += $dels;
    close $F || die "Can't close git diff, $!\n";
}
close $FH || die "Can't close, $!,";

printf "Authors      : %4d\n", $authors;
printf "Commits      : %4d\n", $total;
printf "Files        : %4d (%.2f average)\n", $tot_files, $tot_files / $total;
printf "Added lines  : %4d (%.2f average)\n", $tot_adds, $tot_adds / $total;
printf "Deleted lines: %4d (%.2f average)\n", $tot_dels, $tot_dels / $total;
my $tot = $tot_adds - $tot_dels;
printf "Net change   : %4d (%.2f average)\n", $tot, $tot / $total;
