#! /usr/bin/env python
"""get-followups

Get list of users (in CSV format) who have not been reached.
"""

import mysql.connector
import datetime, os, re, subprocess, sys, string, random
import getopt

urlbase = 'https://license.openssl.org/cgi-bin/lookup.py?uid='
dbconfig = {
        'user': 'licensereader',
        'password': open('ropass.txt').read().strip(),
        'database': 'license'
        }
conn = mysql.connector.connect(**dbconfig)
cursor = conn.cursor()

single = 0
opts, args = getopt.getopt(sys.argv[1:], "")
for o,a in opts:
    print __doc__
    raise SystemExit

q = ('SELECT users.uid,email,reply,name,count(log.uid) FROM users'
        ' LEFT JOIN log ON log.uid = users.uid'
        ' WHERE reply = "-" GROUP BY email' )
cursor.execute(q)
fmtstring = urlbase + '%d, %s, %d, "%s"'
for row in cursor:
    uid,email,reply,name,count = row
    print fmtstring % (uid, email, count, name)
