#! /usr/bin/env python
"""Arguments is a list of SQL paterns (will get wrapped in wildcards, %)
and send them license agreement email.
"""

import mysql.connector
import datetime, os, re, subprocess, sys, string, random

dbconfig = {
        'user': 'license',
        'password': open('rwpass.txt').read().strip(),
        'database': 'license'
        }
conn = mysql.connector.connect(**dbconfig)
cursor = conn.cursor()
raw = open("request-approval.txt").read()

# Get dict of matching users
who = {}
for email in sys.argv[1:]:
    q = 'SELECT email,uid,secret FROM users WHERE email LIKE %s'
    pat = '%' + email + '%'
    cursor.execute(q, (pat,))
    for row in cursor:
        email,uid,secret = row
        who[email] = (uid,secret)

for email in who:
    print email
    uid, secret = who[email]
    d = { 'uid': uid, 'secret': secret }
    args = ('mail', '-s', 'OpenSSL License change',
            '-r', 'license@openssl.org', email)
    f = subprocess.Popen(args, stdin=subprocess.PIPE).stdin
    print >>f, raw % d
    f.close()
    today = datetime.datetime.today().date()
    t = 'UPDATE users SET last_asked=%s WHERE uid=%s'
    cursor.execute(t, (today, uid))
    conn.commit()
    #print raw % d
