/*
 * Copyright 2024 The OpenSSL Project Authors. All Rights Reserved.
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 *
 * !!!    D O   N O T   E D I T    !!!
 * This file is generated by genkeys-setpeer.sh script.
 */

#define PEM_DH	\
    "-----BEGIN PRIVATE KEY-----\n"\
    "MIIBPwIBADCCARcGCSqGSIb3DQEDATCCAQgCggEBAP//////////rfhUWKK7Spqv\n"\
    "3FYgJz088di5xYPOLTaVqeE2QRRkM/vMk53OJJs++X0v42NjDHXY9oGyAq7EYXrT\n"\
    "3x7V1f1lYSQz9R9fBm7QhWNlVT3tGvO1VxNef1fJNZhPDHDg5ot34qaJ2vPv6HId\n"\
    "8VihNq3nNTCsyk9IOnl6vAqxgrMk+2HRCKlLssjj+7lq2rdg1/RoHU9Co945TfSu\n"\
    "Vu3nY3K7GQsHp8juCm1wngL84c334uzANATNKDQvYZFy/pzphYP/jk8SMu7ygYPD\n"\
    "/jsbTG+tczu1/LwuwiAFxY7xg30Wg7LG80omwbLv+ohrQjhhKFyX//////////8C\n"\
    "AQIEHwIdAR0rKC/sXr/2nEJdzCv5cvXsVP/GRdi5lJQuEFE=\n"\
    "-----END PRIVATE KEY-----\n"

#define PEM_EC256	\
    "-----BEGIN PRIVATE KEY-----\n"\
    "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgcjg2HMtc+QP4vGlC\n"\
    "0Hw8b8rBgUEiAaA+2+P2zeNZZ7mhRANCAARv+YJqfouBMhVF7NzjSZmX5W+hSfQ6\n"\
    "OFPmXiKNG0NwLn4x2cpdFr7lB3pKXcQCA+gPJwUX8wwLa/U76EKsi0jy\n"\
    "-----END PRIVATE KEY-----\n"

#define PEM_EC521	\
    "-----BEGIN PRIVATE KEY-----\n"\
    "MIHuAgEAMBAGByqGSM49AgEGBSuBBAAjBIHWMIHTAgEBBEIBWGeG6pd7lrREvn2h\n"\
    "Z1mjK7p0qV7lWU0Aqk6hSEsMM+FvCMieJatNSJTTObaea3dZcvbpls+C2RTgGr9y\n"\
    "qErEfNGhgYkDgYYABAAN636e/RKKVK/kasjwY93+sLwS5PkdIQ3MWwoc/nGb791B\n"\
    "P817rhEdbBsdLHq/MrbednUSaYU1DDpmpo5Zc9Wf7QD1yQSJyr/v9d3hcyE/YrVk\n"\
    "W3kyGsOWxlXqdOEsGrSgC+lZZqYXJuH1WxoLcIFxb58MJ5CBYuaxOy3dv/SeQiXc\n"\
    "NQ==\n"\
    "-----END PRIVATE KEY-----\n"

#define PEM_X25519	\
    "-----BEGIN PRIVATE KEY-----\n"\
    "MC4CAQAwBQYDK2VuBCIEIBBDVCtCXFW/G0EfSyF5jh/4NEW2/8YkK4GaUnSGmU57\n"\
    "-----END PRIVATE KEY-----\n"

static const char *sample_keys[] = {
    PEM_DH,
    PEM_EC256,
    PEM_EC521,
    PEM_X25519,
    NULL
};

static const size_t sample_key_sizes[] = {
    sizeof(PEM_DH) - 1,
    sizeof(PEM_EC256) - 1,
    sizeof(PEM_EC521) - 1,
    sizeof(PEM_X25519) - 1,
};

enum {
    SAMPLE_DH,
    SAMPLE_EC256,
    SAMPLE_EC521,
    SAMPLE_X25519,
    SAMPLE_ALL,
    SAMPLE_INVALID
};

static const char *sample_names[] = {
    "dh",
    "ec256",
    "ec521",
    "x25519",
    "all",
    NULL
};
